name: CI

on:
  push:
    branches: [deploy]
  pull_request:
    branches: [deploy]

jobs:

  create-envfile:
 
    runs-on: ubuntu-latest
 
    steps:
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_DEBUG: false
        envkey_GATSBY_GITHUB_API_TOKEN: ${{ secrets.GATSBY_GITHUB_API_TOKEN}}
        some_other_variable: foobar
        directory: <directory_name>
        file_name: .env
        fail_on_empty: false
      
